### ISSUE TITLE
Question about PWM coding

### ISSUE THREAD

**Issue by EagleYK** [remrc/Self-Balancing-Cube#10]
Hi, I saw in the code below you put 255-pwm as final results. Does it mean Nidec motor sets lower PWM but getting high motor speed?
 >>> pwmSet(PWM1_CH, sp > 255 ? 255 : 255 - sp);
THX a lot.

**Comment by remrc** [comment]
Nidec PWM is inverse.

**Comment by EagleYK** [comment]
> Nidec PWM is inverse.

Thanks a lot it really helps.
