### ISSUE TITLE
Encoder Voltage Incorrect in Schematic

### ISSUE THREAD

**Issue by mpaw** [remrc/Self-Balancing-Cube#15]
In the schematic you have the power supply of the encoder on the Nidec motor connected to 3.3V on the ESP32. Power supply of the encoder should be 5V.

![image](https://github.com/user-attachments/assets/a045d9b2-aa78-47c3-b2b5-6044bc5d1652)

**Comment by remrc** [comment]
Yes, but encoders work fine with 3.3V.
