### ISSUE TITLE
Battery voltage question

### ISSUE THREAD

**Issue by jcleek** [remrc/Self-Balancing-Cube#17]
Battery buzzer isn't going off at low voltage. Comment in code says "value 204 must be selected by measuring battery voltage!" but I am unsure what this measurement is.

**Comment by remrc** [comment]
This value should be selected so that the beeping begins at ~9.5V.

**Comment by jcleek** [comment]
Sorry, I mean where did you get the value "204"? What is that?

**Comment by remrc** [comment]
Of course, by changing the voltage and printing measured value.  The analog inputs on the ESP32 must not exceed a voltage of 3.3V. I need to measure ~9-13V.
