### ISSUE TITLE
schematic missing information

### ISSUE THREAD

**Issue by SnippetsUnlimited** [remrc/Self-Balancing-Cube#5]
The schematic shows use of a transistor for the buzzer but there is no transistor number mentioned on the schematic. Can you suggest the transistor number/model used and the pin connections. I am just a hobbyist and do not have knowledge enough to know by myself, what kind of transistor I should utilize here.

Thanks-

**Comment by remrc** [comment]
You can use PN2222 or something similar (n-p-n).

**Comment by SnippetsUnlimited** [comment]
I do not have PN2222 available but but it seems that I can use the available alternative 2N2222.

Thanks for the help!!
