### ISSUE TITLE
Regulator adjustment over BT missing from esp32_cube_enc code

### ISSUE THREAD

**Issue by alekoy** [remrc/Self-Balancing-Cube#9]
Adjusting the PIDs is not possible over BT when using the encoder-program, as there is no coding for it,
Had to adjust the K and eK-values in the ESP21.h file and re-flash the esp for each adjustment.

I tried tuning it for some time before I discovered this and have gotten my cube to balance pretty good, so this comment is meant as a heads up for anyone trying to adjust it using the method shown in the youtube-video.

**Comment by remrc** [comment]
Yes, I removed this part of code.
